services:
  playwright:
    container_name: patchright-scrape-api
    build: .
    ports:
      - "3003:3003"
    environment:
      - DOMAIN_BLOCKED_DOMAINS=
      - DOMAIN_BLOCKLIST_URL=
      - DOMAIN_BLOCKLIST_PATH=blocklist.txt
      - RESOURCES_BLOCKED=['image', 'stylesheet', 'media', 'font','other']
      - PROXY_SERVER=
      - PROXY_USERNAME=
      - PROXY_PASSWORD=
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL