services:
  playwright:
    container_name: playwright-scrape-api
    build: .
    ports:
      - "3003:3003"
    environment:
      - BLOCK_MEDIA=True
      - PROXY_SERVER=
      - PROXY_USERNAME=
      - PROXY_PASSWORD=
      #- ADS_BLOCKLIST_URL=https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/multi.txt
      - ADS_BLOCKLIST_PATH=blocklist.txt
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL