services:
  patchright:
    container_name: patchright-scrape-api
    build: .
    ports:
      - "3000:3000"
    environment:
      - DOMAIN_BLOCKED_DOMAINS=
      - DOMAIN_BLOCKLIST_URL=
      - DOMAIN_BLOCKLIST_PATH=blocklist.txt
      - RESOURCES_BLOCKED=['image', 'stylesheet', 'media', 'font','other']
      - PROXY_SERVER=
      - PROXY_USERNAME=
      - PROXY_PASSWORD=
      - PORT=3000
      - PERSISTENT_CONTEXT=False
      - REMOTE_CDP=
    volumes:
      - patchright_context:/context # needed if PERSISTENT_CONTEXT=True
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL

volumes:
  patchright_context: