name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push default image
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: BUILD_TYPE=default
          tags: ${{ github.repository }}:latest

      -
        name: Build and push lite image
        uses: docker/build-push-action@v6
        with:
          build-args: BUILD_TYPE=lite
          push: true
          tags: ${{ github.repository }}:lite-latest
